import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from 'next-themes'

//IBM Plex Mono
const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibmPlexMono.variable} antialiased`}
      >
        <ThemeProvider 
            defaultTheme="dark"
            disableTransitionOnChange
            >
          <Navbar />
          <div className="relative">
            <div className="-z-1 absolute -top-40 -left-40 w-[500px] h-[500px] rounded-full bg-blue-900/20 blur-[100px]"/>
            <div className="-z-1 absolute -bottom-40 -left-40 w-[500px] h-[500px] rounded-full bg-blue-900/20 blur-[100px]"/>
            <div className="-z-1 absolute top-0 right-0 w-[500px] h-[500px] rounded-full bg-blue-900/20 blur-[100px]"/>
            <div className="-z-1 absolute bottom-0 right-0 w-[500px] h-[500px] rounded-full bg-blue-900/20 blur-[100px]"/>
            <div className="p-2 desktop:max-w-[1280px] laptop:max-w-[1024px] tablet:max-w-[768px] mx-auto">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
